export { FloatProxy } from "./FloatProxy";
export { Vector2Proxy } from "./Vector2Proxy";
export { Vector3Proxy } from "./Vector3Proxy";
export { BooleanProxy } from "./BooleanProxy";
export { IComponentProxy } from "./IComponentProxy";
export { ComponentProxy } from "./ComponentProxy";
export { SizeProxy } from "./SizeProxy";
export { AccelerationProxy } from "./AccelerationProxy";
export { IndexProxy } from "./IndexProxy";